/* PEPTORA editorial context, reviewed 2026-09-25.
 * Community vocabulary describes interests and claims, not proven benefits.
 * Entries: name, EN summary, ES summary, EN context, ES context, EN boundary, ES boundary.
 * Keep exact registry names; no dosing, administration or combination protocols.
 */
const PEPTORA_COMMUNITY = Object.fromEntries([
['Semaglutide',
 'Less “food noise”, appetite control and sustainable fat loss: the goals behind the GLP-1 conversation.',
 'Menos “food noise”, control del apetito y pérdida de grasa sostenible: los objetivos de la conversación GLP-1.',
 'Food noise means the persistent mental chatter around food. In body-composition discussions, the interest is not just a lower scale weight: it is managing hunger while maintaining strength, muscle and adequate nutrition. Those are separate outcomes, not automatic consequences of weight loss.',
 'Food noise es ese ruido mental constante alrededor de la comida. En composición corporal, el interés no es solo bajar en la báscula: es manejar el hambre sin descuidar fuerza, músculo y nutrición. Son objetivos distintos, no consecuencias automáticas de perder peso.',
 'Clinical results concern specific medicines and populations. They do not establish the quality or safety of a research-labelled vial.',
 'Los resultados clínicos corresponden a medicamentos y poblaciones concretas; no certifican la calidad ni seguridad de un vial de investigación.'],
['Tirzepatide',
 'Appetite, glucose and “recomp”: why dual GIP/GLP-1 signalling attracts attention beyond the scale.',
 'Apetito, glucosa y “recomp”: por qué la señalización dual GIP/GLP-1 interesa más allá de la báscula.',
 'Recomp is shorthand for changing the balance of fat and lean mass. The community conversation connects reduced hunger and metabolic health with keeping training performance. Dual agonism describes two receptor targets; it does not mean twice the benefit or guaranteed muscle preservation.',
 'Recomp es la forma abreviada de hablar de recomposición: cambiar la proporción de grasa y masa magra. La conversación conecta menor hambre y salud metabólica con conservar el rendimiento al entrenar. Agonismo dual significa dos receptores, no el doble de beneficio ni preservación muscular garantizada.',
 'Compare outcomes and adverse effects in actual trials, not receptor counts or before-and-after photographs.',
 'Compara resultados y efectos adversos en ensayos, no el número de receptores ni fotografías de antes y después.'],
['Retatrutide',
 '“Reta” and the triple-agonist conversation: appetite, energy balance and the search for better body composition.',
 '“Reta” y la conversación del triple agonista: apetito, balance energético y búsqueda de una mejor composición corporal.',
 'Its three targets—GLP-1, GIP and glucagon receptors—make it a frequent comparison point with tirzepatide. Biohacking interest centres on fat loss and metabolic flexibility, meaning how the body handles different energy sources. A more complex mechanism is not a ranking of safety or suitability.',
 'Sus tres blancos —receptores GLP-1, GIP y glucagón— la vuelven un punto de comparación con tirzepatide. El interés gira alrededor de perder grasa y de la flexibilidad metabólica: cómo maneja el cuerpo distintas fuentes de energía. Un mecanismo más complejo no significa que sea más seguro o adecuado.',
 'Published trial results are not personal forecasts. Research products are not equivalent to the formulation studied in a trial.',
 'Los resultados publicados no predicen un resultado personal. Un producto de investigación no equivale a la formulación estudiada en un ensayo.'],
['Cagrilintide',
 'Satiety and “feeling satisfied”: the amylin side of the appetite conversation, distinct from GLP-1.',
 'Saciedad y “sentirse satisfecho”: el lado de la amilina en la conversación del apetito, distinto de GLP-1.',
 'The interest is the feeling that a meal is enough, rather than a stimulant-style energy boost. It appears alongside semaglutide in CagriSema discussions because the pathways differ. That research pairing is not an invitation to build a personal stack.',
 'El interés está en sentir que una comida es suficiente, no en un impulso de energía tipo estimulante. Aparece junto a semaglutide en conversaciones sobre CagriSema porque sus vías son diferentes. Esa combinación de investigación no es una invitación a armar un stack personal.',
 'Evidence for a studied combination cannot be transferred to arbitrary mixtures, ratios or commercial labels.',
 'La evidencia de una combinación estudiada no se transfiere a mezclas, proporciones o etiquetas comerciales arbitrarias.'],
['Mazdutide',
 'A different dual agonist: metabolic health, body composition and the GLP-1/glucagon discussion.',
 'Otro agonista dual: salud metabólica, composición corporal y la conversación GLP-1/glucagón.',
 'The attraction is the idea of connecting appetite regulation with energy metabolism. Unlike tirzepatide, its second receptor target is glucagon rather than GIP. Knowing that distinction makes comparisons more useful than grouping every multi-agonist under “stronger GLP-1”.',
 'El atractivo es conectar la regulación del apetito con el metabolismo energético. A diferencia de tirzepatide, su segundo receptor es el de glucagón, no GIP. Entender esa diferencia ayuda más que agrupar todos los multiagonistas como “un GLP-1 más fuerte”.',
 'Study populations, endpoints and tolerability matter more than informal potency rankings.',
 'La población estudiada, los resultados medidos y la tolerabilidad importan más que los rankings informales de potencia.'],
['Survodutide',
 'Metabolic health meets liver research: why this GLP-1/glucagon agonist enters the fat-loss conversation.',
 'Salud metabólica e investigación hepática: por qué este agonista GLP-1/glucagón aparece al hablar de pérdida de grasa.',
 'The discussion extends beyond visible body fat to liver health and metabolic dysfunction. This is a useful distinction: a change in weight, liver fat or a liver-disease endpoint answers a different question. It should not be described as a generic “liver detox”.',
 'La conversación va más allá de la grasa visible y llega a la salud del hígado y la disfunción metabólica. Un cambio de peso, de grasa hepática o de una variable de enfermedad hepática responde preguntas diferentes. No equivale a un “detox del hígado”.',
 'Liver-disease research does not establish a general wellness benefit in healthy people.',
 'La investigación de enfermedad hepática no demuestra un beneficio general de bienestar en personas sanas.'],
['GLP-1',
 'The vocabulary behind “food noise”, satiety and metabolic health—not the name of one interchangeable product.',
 'El vocabulario detrás del “food noise”, la saciedad y la salud metabólica; no un producto único e intercambiable.',
 'GLP-1 is a natural signalling peptide. Online, “GLP-1s” often means a wider drug category, including molecules with additional receptor targets. First identify the molecule: semaglutide, tirzepatide and retatrutide are not simply different strengths of the same compound.',
 'GLP-1 es un péptido de señalización natural. En línea, “los GLP-1” suele referirse a una categoría más amplia, incluso a moléculas con otros receptores. Primero identifica la molécula: semaglutide, tirzepatide y retatrutide no son distintas potencias del mismo compuesto.',
 'A class nickname cannot specify a product’s identity, evidence, formulation or risks.',
 'El apodo de una categoría no identifica el producto, su evidencia, formulación ni riesgos.'],
['5-Amino-1MQ',
 '“Metabolic flexibility” and fat-loss discussions through NNMT inhibition, rather than appetite-receptor signalling.',
 '“Flexibilidad metabólica” y pérdida de grasa mediante la inhibición de NNMT, no mediante receptores del apetito.',
 'The appeal is a different angle on cellular energy handling. It is a small molecule, not a peptide, and is often discussed alongside body-composition goals. Animal findings are the starting point for questions, not proof of a metabolism boost in people.',
 'El atractivo es una vía distinta para estudiar cómo maneja energía la célula. Es una molécula pequeña, no un péptido, y se comenta junto a objetivos de composición corporal. Los hallazgos animales abren preguntas; no prueban un impulso metabólico en personas.',
 'Preclinical weight changes do not establish effective or safe human fat loss.',
 'Los cambios de peso preclínicos no establecen pérdida de grasa eficaz ni segura en humanos.'],
['Lipo-C',
 'The “lipotropic blend” conversation: energy and body composition, with a formula that must be identified first.',
 'La conversación de los “lipotrópicos”: energía y composición corporal, con una fórmula que primero hay que identificar.',
 'Lipo-C is a formulation label, not a single defined peptide. The appeal is usually framed around fat metabolism and everyday energy. Ingredient lists can differ, so two products with the same name may not be comparable; the label alone cannot explain their effects.',
 'Lipo-C es el nombre de una formulación, no un péptido único definido. Suele presentarse alrededor del metabolismo de grasas y la energía cotidiana. Los ingredientes pueden variar: dos productos con el mismo nombre no necesariamente son comparables ni producen los mismos efectos.',
 '“Lipotropic” is not proof of fat loss. Ingredient identity and product-specific evidence come first.',
 '“Lipotrópico” no prueba pérdida de grasa. Primero van la identidad de los ingredientes y la evidencia del producto concreto.'],
['Lipo-C + B12',
 'A lipotropic blend plus B12: why “energy support” and fat loss should be read as different claims.',
 'Una mezcla lipotrópica con B12: por qué “apoyo energético” y pérdida de grasa son afirmaciones distintas.',
 'Adding B12 attracts people looking for less fatigue as well as body-composition changes. Correcting a vitamin deficiency is a different clinical question from boosting energy when levels are adequate. Neither the vitamin nor the blend name establishes a fat-burning effect.',
 'La B12 atrae a quienes buscan menos cansancio además de cambios de composición corporal. Corregir una deficiencia vitamínica es una pregunta clínica distinta de aumentar energía con niveles adecuados. Ni la vitamina ni el nombre de la mezcla demuestran un efecto quemagrasa.',
 'A vitamin ingredient does not validate the full blend or make it risk-free.',
 'Que contenga una vitamina no valida toda la mezcla ni la vuelve libre de riesgos.'],
['CJC-1295 (No DAC)',
 'GH pulses, recovery and “recomp”: the short-acting GHRH conversation, often discussed alongside ipamorelin.',
 'Pulsos de GH, recuperación y “recomp”: la conversación de GHRH de acción corta, frecuentemente junto a ipamorelin.',
 'The community interest is encouraging the body’s own GH signalling rather than supplying GH itself. “No DAC” is commonly used for modified GRF(1–29); it should not be confused with long-acting CJC-1295 with DAC. Sleep, recovery and lean-mass goals remain separate claims to evaluate.',
 'El interés es estimular la señalización propia de GH en lugar de aportar GH directamente. “No DAC” suele usarse para GRF(1–29) modificado; no debe confundirse con CJC-1295 con DAC de acción prolongada. Sueño, recuperación y masa magra son afirmaciones distintas que requieren evaluación.',
 'Long-acting CJC-1295 studies cannot validate a no-DAC product or its combination with ipamorelin.',
 'Los estudios de CJC-1295 de acción prolongada no validan un producto sin DAC ni su combinación con ipamorelin.'],
['CJC-1295 (With DAC)',
 'Longer GH-axis exposure: the key distinction behind the “with DAC” label in performance discussions.',
 'Mayor duración en el eje GH: la diferencia clave del “con DAC” en conversaciones de rendimiento.',
 'DAC changes the exposure profile, which is why this is not just another name for the no-DAC reference. Biohackers discuss recovery and body composition around GH/IGF-1 signalling, but a sustained hormone response is a biomarker observation, not proof of better training results.',
 'DAC cambia el perfil de exposición; por eso no es otro nombre para la referencia sin DAC. Se habla de recuperación y composición corporal alrededor de GH/IGF-1, pero una respuesta hormonal sostenida es un cambio de biomarcador, no prueba de mejores resultados al entrenar.',
 'Endocrine changes require clinical interpretation; “longer acting” does not mean safer or more useful.',
 'Los cambios endocrinos requieren interpretación clínica; “más duradero” no significa más seguro ni más útil.'],
['Ipamorelin',
 'Recovery, sleep quality and lean-mass goals drive interest in this GH-secretagogue reference.',
 'Recuperación, calidad del sueño y masa magra explican el interés en esta referencia de secretagogos de GH.',
 'A secretagogue stimulates release of a hormone; it is not the hormone itself. Ipamorelin is discussed through the ghrelin receptor, while GHRH analogues approach GH signalling differently. The proposed pairing is often called a stack, but biological rationale is not clinical proof of synergy.',
 'Un secretagogo estimula la liberación de una hormona; no es la hormona. Ipamorelin se comenta por el receptor de grelina, mientras los análogos de GHRH actúan por otra vía. Esa combinación suele llamarse stack, pero una lógica biológica no demuestra sinergia clínica.',
 'A GH response alone does not establish better sleep, injury recovery or muscle gain.',
 'Una respuesta de GH por sí sola no demuestra mejor sueño, recuperación de lesiones ni ganancia muscular.'],
['Sermorelin Acetate',
 '“Support your own GH”: the phrase behind interest in recovery, sleep and healthy-aging conversations.',
 '“Estimular tu propia GH”: la idea detrás del interés en recuperación, sueño y envejecimiento saludable.',
 'Sermorelin is a GHRH-related reference, not replacement GH. Its appeal is often framed as working with an existing hormone axis. “Endogenous” means produced by the body; it does not mean that modifying the signal is automatically natural, necessary or safe.',
 'Sermorelin es una referencia relacionada con GHRH, no GH de reemplazo. Su atractivo se plantea como actuar sobre un eje hormonal existente. “Endógeno” significa producido por el cuerpo; modificar esa señal no resulta automáticamente natural, necesario ni seguro.',
 'A medical endocrine context cannot be replaced by an age-based “optimization” claim.',
 'El contexto endocrino médico no se sustituye con una promesa de “optimización” basada solo en la edad.'],
['Hexarelin Acetate',
 'A “strong GH signal” is the attraction in performance circles—but potency is not a complete benefit profile.',
 'Una “señal fuerte de GH” atrae en el entorno de rendimiento, pero potencia no equivale a un perfil completo de beneficios.',
 'Hexarelin belongs to the GH-releasing peptide conversation. People compare it with ipamorelin and GHRP-6 when discussing recovery or muscle-oriented goals. Those comparisons need to separate receptor activity, other endocrine effects and actual functional outcomes rather than treating them as a strength ladder.',
 'Hexarelin pertenece a la conversación de péptidos liberadores de GH. Se compara con ipamorelin y GHRP-6 al hablar de recuperación o desarrollo muscular. Conviene separar actividad del receptor, otros efectos endocrinos y resultados funcionales, no tratarlos como una escala de potencia.',
 'More hormone release does not establish more recovery or a favourable risk–benefit balance.',
 'Liberar más hormona no demuestra mayor recuperación ni un balance favorable entre riesgos y beneficios.'],
['GHRP-6 Acetate',
 'GH signalling and hunger: why appetite is central to the “bulking” discussion around GHRP-6.',
 'Señalización de GH y hambre: por qué el apetito es central en la conversación de “volumen” alrededor de GHRP-6.',
 'Bulking means trying to gain body mass, usually with a muscle-building goal. GHRP-6 enters this conversation through ghrelin-related signalling and GH release. An appetite effect, a hormone change and new muscle are three different outcomes; one cannot stand in for the others.',
 'Hacer volumen significa buscar aumentar masa corporal, generalmente con un objetivo muscular. GHRP-6 aparece por la señalización relacionada con grelina y la liberación de GH. Un cambio de apetito, uno hormonal y ganar músculo son tres resultados distintos; no son equivalentes.',
 'The community goal is not evidence of selective lean-mass gain or suitability for appetite problems.',
 'El objetivo comunitario no demuestra ganancia selectiva de masa magra ni idoneidad para problemas de apetito.'],
['Tesamorelin',
 'Visceral fat—not simply “belly fat”: the distinction that makes tesamorelin a body-composition reference.',
 'Grasa visceral, no simplemente “grasa abdominal”: la distinción que hace relevante a tesamorelin en composición corporal.',
 'Visceral fat sits around internal organs; subcutaneous fat sits under the skin. The biohacking interest is a change in fat distribution and metabolic health rather than just a lower scale weight. A smaller waist or a leaner photograph cannot identify which fat compartment changed.',
 'La grasa visceral rodea los órganos; la subcutánea está debajo de la piel. El interés en biohacking es cambiar la distribución de grasa y la salud metabólica, no solo bajar de peso. Una cintura menor o una fotografía más definida no identifican qué compartimento cambió.',
 'Trials concern defined clinical populations. They do not establish general abdominal spot reduction or a universal fat-loss tool.',
 'Los ensayos corresponden a poblaciones clínicas definidas. No demuestran reducción localizada universal ni una herramienta general para perder grasa.'],
['HGH 191AA (Somatropin)',
 'Recovery, lean mass and “anti-aging” claims surround GH, but replacement medicine and enhancement are different questions.',
 'Recuperación, masa magra y promesas “anti-aging” rodean a la GH; reemplazo médico y mejora de rendimiento son preguntas distintas.',
 'Somatropin is growth hormone itself, unlike compounds that stimulate its release. Performance discussions often equate lean mass with muscle function, although fluid and other non-fat tissues also affect that measurement. A laboratory hormone value does not diagnose a need for replacement.',
 'Somatropina es la propia hormona de crecimiento, a diferencia de compuestos que estimulan su liberación. Se suele equiparar masa magra con función muscular, aunque agua y otros tejidos también influyen en esa medición. Un valor hormonal aislado no diagnostica necesidad de reemplazo.',
 'Prescription indications do not validate non-medical performance use; glucose and other systemic effects matter.',
 'Las indicaciones médicas no validan usos no médicos de rendimiento; importan los efectos sobre glucosa y otros sistemas.'],
['HGH Fragment 176-191',
 'The “fat-loss fragment” idea: interest in a piece of GH rather than the full hormone.',
 'La idea del “fragmento para perder grasa”: interés en una parte de GH, no en la hormona completa.',
 'The appeal is separating proposed fat-metabolism effects from the wider growth-hormone signal. That is a research hypothesis, not a guarantee of targeted fat loss. It should also be distinguished from AOD-9604 rather than assuming all GH fragments have identical evidence.',
 'El atractivo es separar posibles efectos sobre metabolismo de grasa de la señal más amplia de GH. Es una hipótesis de investigación, no una garantía de pérdida localizada. También debe distinguirse de AOD-9604: no todos los fragmentos de GH tienen evidencia idéntica.',
 'Being a fragment does not establish human efficacy or remove safety uncertainties.',
 'Ser un fragmento no demuestra eficacia humana ni elimina las incertidumbres de seguridad.'],
['IGF-1 LR3',
 'Hypertrophy and “growth signalling”: the muscle-oriented interest in a modified IGF-1 reference.',
 'Hipertrofia y “señal de crecimiento”: el interés muscular en una referencia modificada de IGF-1.',
 'Hypertrophy means an increase in muscle-fibre size. LR3 is discussed because it differs from native IGF-1, not because it selectively knows where muscle growth is wanted. IGF signalling affects more than muscle, so a growth-pathway argument is incomplete without systemic context.',
 'Hipertrofia significa aumentar el tamaño de las fibras musculares. LR3 se comenta por sus diferencias con IGF-1 natural, no porque seleccione dónde se desea crecer. La señalización IGF afecta más que músculo; hablar de crecimiento sin contexto sistémico queda incompleto.',
 'An experimental analogue is not equivalent to an approved IGF medicine; hypoglycaemia and broader growth effects are relevant concerns.',
 'Un análogo experimental no equivale a un medicamento IGF aprobado; importan la hipoglucemia y los efectos de crecimiento más amplios.'],
['IGF-DES',
 '“Local growth” is the community claim to scrutinize—not a demonstrated ability to choose which muscle grows.',
 '“Crecimiento local” es la afirmación que conviene revisar, no una capacidad demostrada de elegir qué músculo crece.',
 'IGF-DES is discussed in hypertrophy circles as a shortened IGF-1 variant. The attraction is a more focused growth signal, but molecular differences do not establish precise tissue targeting. A subjective pump, temporary fullness and long-term muscle growth are different observations.',
 'IGF-DES se comenta en hipertrofia como una variante acortada de IGF-1. Atrae la idea de una señal de crecimiento más focalizada, pero las diferencias moleculares no prueban selectividad. El pump, la plenitud temporal y el crecimiento muscular a largo plazo son observaciones distintas.',
 'Local muscle-growth claims and personal-use safety are not established by receptor activity.',
 'La actividad del receptor no demuestra crecimiento muscular localizado ni seguridad para uso personal.'],
['Follistatin',
 '“Myostatin blocker” and the idea of releasing the muscle-growth brake drive interest in follistatin.',
 '“Bloqueador de miostatina” y la idea de quitar un freno al crecimiento muscular explican el interés en follistatin.',
 'The shorthand is appealing but incomplete: follistatin interacts with activin-family biology, not just one muscle switch. Research involving gene delivery, different protein variants or disease models cannot be treated as evidence for every product sold under the same name.',
 'La frase resulta atractiva pero incompleta: follistatin interactúa con la biología de la familia de activinas, no solo con un interruptor muscular. Estudios de terapia génica, variantes proteicas o modelos de enfermedad no validan todo producto vendido con ese nombre.',
 'More tissue growth is not necessarily better function, and the wider endocrine effects cannot be ignored.',
 'Más crecimiento de tejido no necesariamente significa mejor función; los efectos endocrinos más amplios no pueden ignorarse.'],
['BPC-157',
 '“Recovery peptide”, tendon support and gut health: the goals that put BPC-157 on the biohacking map.',
 '“Péptido de recuperación”, tendones y salud intestinal: los objetivos que pusieron a BPC-157 en el mapa del biohacking.',
 'The attraction is getting back to movement, training and daily comfort. Tendon, muscle and gut discussions are often grouped together, even though they involve different tissues and research questions. Feeling less discomfort is also not the same as demonstrating structural repair.',
 'El atractivo es volver al movimiento, al entrenamiento y al bienestar cotidiano. Se agrupan tendones, músculo e intestino aunque sean tejidos y preguntas diferentes. Sentir menos molestia tampoco equivale a demostrar reparación estructural.',
 'The “healing peptide” nickname outruns the human evidence. It is not proof of injury repair or a substitute for assessment.',
 'El apodo “péptido reparador” va más allá de la evidencia humana. No prueba reparación de lesiones ni sustituye una valoración.'],
['TB-500 (Thymosin B4 Acetate)',
 'Mobility, connective tissue and the recovery-stack conversation—often paired in discussion with BPC-157.',
 'Movilidad, tejido conectivo y stacks de recuperación; suele comentarse junto a BPC-157.',
 'The community framing is a broader repair environment rather than one symptom. A key detail is identity: “TB-500” is used inconsistently for thymosin-beta-4-related products. Findings for full-length thymosin beta-4 should not automatically be assigned to a fragment or an unspecified vial.',
 'La idea comunitaria es un entorno de reparación más amplio, no un solo síntoma. La identidad importa: “TB-500” se usa de forma inconsistente para productos relacionados con timosina beta-4. Los hallazgos de la proteína completa no se asignan automáticamente a un fragmento o vial sin caracterizar.',
 'Combining a recovery narrative with BPC-157 does not demonstrate faster healing or safe synergy.',
 'Combinar su narrativa de recuperación con BPC-157 no demuestra reparación más rápida ni sinergia segura.'],
['KPV',
 'Gut comfort, skin calm and inflammatory balance: why KPV appears in recovery and KLOW discussions.',
 'Bienestar intestinal, calma de la piel y equilibrio inflamatorio: por qué KPV aparece en recuperación y KLOW.',
 'KPV is a short peptide discussed through inflammatory signalling. “Calming inflammation” is the community shorthand, but inflammation also has protective and repair roles. Gut symptoms, skin appearance and laboratory inflammatory markers are not interchangeable measures of success.',
 'KPV es un péptido corto comentado por la señalización inflamatoria. “Calmar la inflamación” resume el interés, pero la inflamación también protege y participa en reparar. Síntomas intestinales, apariencia de la piel y marcadores de laboratorio no miden lo mismo.',
 'Early findings do not establish treatment of gut disease, skin disease or a generally “inflamed” state.',
 'Los hallazgos iniciales no establecen tratamiento de enfermedades intestinales, cutáneas ni de un estado genérico de “inflamación”.'],
['GHK-Cu',
 'The copper-peptide conversation: skin quality, collagen, hair and the search for a healthier-looking “glow”.',
 'La conversación del péptido de cobre: calidad de piel, colágeno, cabello y búsqueda de un “glow” más saludable.',
 'Interest centres on the skin’s support structure and repair signals, not merely surface hydration. The crucial distinction is formulation: a topical cosmetic, a cell experiment and a systemic research product are different contexts. Evidence from one cannot be casually transferred to another.',
 'El interés está en la estructura de soporte y las señales de reparación de la piel, no solo en hidratación superficial. La formulación es crucial: un cosmético tópico, un experimento celular y un producto sistémico son contextos distintos. La evidencia no se transfiere sin más entre ellos.',
 'Copper binding and collagen-related biology do not guarantee firmer skin, hair growth or whole-body rejuvenation.',
 'Unir cobre y participar en biología del colágeno no garantiza firmeza, crecimiento capilar ni rejuvenecimiento de todo el cuerpo.'],
['Semax',
 'Focus, mental clarity and learning: the nootropic conversation around Semax is centred on cognitive performance.',
 'Enfoque, claridad mental y aprendizaje: la conversación nootrópica de Semax se centra en rendimiento cognitivo.',
 'Biohackers connect Semax with neuroplasticity—the nervous system’s capacity to adapt—and discuss BDNF-related research. That is different from Selank’s calm-and-stress emphasis. Neither should be reduced to a simple stimulant-versus-sedative pair, and perceived clarity is not a validated memory or productivity gain.',
 'Se conecta Semax con neuroplasticidad —la capacidad del sistema nervioso de adaptarse— y con investigación relacionada con BDNF. Es distinto del énfasis de Selank en calma y estrés. No forman una pareja simple de estimulante y sedante; sentir claridad no prueba mejorar memoria o productividad.',
 'Neurological and preclinical findings do not establish cognitive enhancement in healthy people.',
 'Los hallazgos neurológicos y preclínicos no establecen mejora cognitiva en personas sanas.'],
['Selank',
 'Calm focus, stress resilience and less mental tension: a different conversation from Semax’s performance emphasis.',
 'Enfoque en calma, resiliencia al estrés y menor tensión mental: una conversación distinta al énfasis de rendimiento de Semax.',
 'The goal described is staying mentally present without feeling overwhelmed, rather than pushing stimulation. Its anxiety-related research helps explain that interest. Calm can affect how focus feels, so it is inaccurate to say Selank has nothing to do with cognition or that it is simply Semax’s opposite.',
 'El objetivo descrito es estar mentalmente presente sin sentirse rebasado, no buscar más estimulación. Su investigación relacionada con ansiedad explica ese interés. La calma puede cambiar cómo se percibe el enfoque: sería inexacto decir que no tiene relación con cognición o que es lo opuesto a Semax.',
 'Limited clinical and preclinical work does not establish a self-treatment for anxiety or guarantee non-sedating effects.',
 'El trabajo clínico limitado y preclínico no establece un autotratamiento de ansiedad ni garantiza ausencia de sedación.'],
['Cerebrolysin',
 '“Brain recovery” and neuroplasticity: why a peptide mixture appears in advanced nootropic conversations.',
 '“Recuperación cerebral” y neuroplasticidad: por qué una mezcla de péptidos aparece en conversaciones nootrópicas.',
 'The attraction draws on neurological rehabilitation research, but Cerebrolysin is a complex mixture rather than a single defined nootropic peptide. Recovery after a neurological illness and improving the performance of a healthy brain are very different research questions.',
 'El atractivo parte de investigación en rehabilitación neurológica, pero Cerebrolysin es una mezcla compleja, no un péptido nootrópico único. Recuperarse de una enfermedad neurológica y mejorar el rendimiento de un cerebro sano son preguntas muy diferentes.',
 'Clinical literature in disease cannot establish a general “brain upgrade” or a reliable productivity benefit.',
 'La literatura clínica en enfermedad no demuestra un “upgrade cerebral” general ni un beneficio fiable de productividad.'],
['DSIP',
 'Deep sleep and next-day recovery: the promise people hear in the name “delta sleep-inducing peptide”.',
 'Sueño profundo y recuperación al día siguiente: la promesa que se interpreta del nombre “péptido inductor del sueño delta”.',
 'The name itself encourages a direct sleep claim. Biohacking conversations often connect sleep depth with recovery scores and readiness to train. Time asleep, sleep stages, wearable estimates and feeling refreshed are different measurements; the compound’s name cannot substitute for evidence on any of them.',
 'El nombre invita a suponer un efecto directo sobre el sueño. Se conecta profundidad del descanso con puntuaciones de recuperación y disposición para entrenar. Duración, fases, estimaciones del reloj y sentirse descansado son medidas distintas; el nombre no sustituye evidencia sobre ninguna.',
 'The research record is limited and mixed; it does not establish predictable deep sleep or treatment of insomnia.',
 'La investigación es limitada y mixta; no establece sueño profundo predecible ni tratamiento del insomnio.'],
['Ara-290',
 'Nerve comfort and recovery: the interest around ARA-290, also known as cibinetide.',
 'Bienestar nervioso y recuperación: el interés alrededor de ARA-290, también conocido como cibinetide.',
 'It enters discussions of small-fibre nerves and protective signalling, rather than muscle building. Its relationship to erythropoietin can be confusing: an EPO-derived research peptide should not be equated with EPO’s blood-cell effects or an endurance-enhancement strategy.',
 'Aparece al hablar de fibras nerviosas pequeñas y señales protectoras, no de desarrollo muscular. Su relación con eritropoyetina puede confundir: un péptido derivado de EPO no equivale a sus efectos sobre células sanguíneas ni a una estrategia para aumentar resistencia.',
 'Indication-specific nerve research does not establish relief of undiagnosed pain or a general recovery effect.',
 'La investigación nerviosa en indicaciones concretas no demuestra alivio de dolor sin diagnóstico ni recuperación general.'],
['MOTS-c',
 'Metabolic flexibility, endurance and “exercise mimetic” claims explain the excitement around this mitochondrial peptide.',
 'Flexibilidad metabólica, resistencia y el término “mimético del ejercicio” explican el interés en este péptido mitocondrial.',
 'The attraction is how muscle and mitochondria respond to energy demand. Metabolic flexibility means adapting fuel use to the situation. Exercise-related observations in humans and experiments administering MOTS-c to animals are different types of evidence; neither makes a research vial a replacement for training.',
 'El atractivo es cómo músculo y mitocondrias responden a la demanda de energía. Flexibilidad metabólica significa adaptar el uso de combustible a la situación. Observar respuestas al ejercicio en humanos y administrar MOTS-c a animales son evidencias distintas; ninguna convierte un vial en sustituto del entrenamiento.',
 'The “exercise in a vial” phrase is not an established human performance outcome.',
 'La frase “ejercicio en un vial” no es un resultado demostrado de rendimiento humano.'],
['SS-31',
 'Mitochondrial efficiency and cellular resilience: why SS-31 enters energy and healthspan discussions.',
 'Eficiencia mitocondrial y resiliencia celular: por qué SS-31 aparece en conversaciones de energía y healthspan.',
 'Also known as elamipretide, this reference is discussed around the mitochondrial membrane rather than as a stimulant. Healthspan means years lived with good function, not simply a longer life. Clinical development and a disease-specific medicine are distinct from broad anti-aging claims.',
 'También llamado elamipretide, se comenta por la membrana mitocondrial, no como estimulante. Healthspan significa años vividos con buena función, no solo vivir más. El desarrollo clínico y un medicamento para una enfermedad concreta son distintos de promesas generales anti-aging.',
 'The US Forzinity indication concerns Barth syndrome in patients meeting its label criteria; it does not validate longevity use or research-vial equivalence.',
 'La indicación estadounidense de Forzinity corresponde al síndrome de Barth bajo criterios de su ficha; no valida usos de longevidad ni equivalencia con viales de investigación.'],
['NAD+',
 'Cellular energy, “brain fog” and healthy aging: the goals that make NAD+ a familiar biohacking term.',
 'Energía celular, “niebla mental” y envejecimiento saludable: los objetivos que vuelven familiar a NAD+ en biohacking.',
 'NAD+ is a cofactor, not a peptide or a direct measure of how energetic someone feels. Conversations often mix NAD+ with its precursors NR and NMN. Changing a measured metabolite, feeling more alert and improving long-term function are separate outcomes—and different products need different evidence.',
 'NAD+ es un cofactor, no un péptido ni una medida directa de cuánta energía siente alguien. Se mezcla en conversaciones con sus precursores NR y NMN. Cambiar un metabolito, sentirse más alerta y mejorar función a largo plazo son resultados distintos; cada producto requiere su evidencia.',
 'Evidence for a precursor cannot prove the benefits of NAD+ itself, and a biomarker change is not demonstrated rejuvenation.',
 'La evidencia de un precursor no prueba beneficios del propio NAD+; cambiar un biomarcador no demuestra rejuvenecimiento.'],
['L-Carnitine',
 'Fat transport, training energy and body composition: understanding the “fat-burning” shorthand.',
 'Transporte de grasas, energía al entrenar y composición corporal: entender la frase “quemar grasa”.',
 'Carnitine helps move long-chain fatty acids into mitochondria. That normal biological role explains the interest, but transporting fuel is not the same as losing body fat. Deficiency, diet, training and formulation all change the question being studied; it is not a peptide.',
 'La carnitina ayuda a trasladar ácidos grasos de cadena larga a las mitocondrias. Esa función explica el interés, pero transportar combustible no equivale a perder grasa corporal. Deficiencia, dieta, entrenamiento y formulación cambian la pregunta estudiada; no es un péptido.',
 'A normal metabolic function does not guarantee extra fat loss or better performance from supplementation.',
 'Una función metabólica normal no garantiza pérdida extra de grasa ni mayor rendimiento al suplementar.'],
['AOD-9604',
 'A “fat-metabolism peptide” in body-composition discussions, distinct from full growth hormone.',
 'Un “péptido de metabolismo de grasas” en composición corporal, distinto de la hormona de crecimiento completa.',
 'The attraction is the idea of isolating a fat-related part of GH biology without reproducing all of GH’s actions. It is a modified fragment, not interchangeable with every product labelled HGH fragment. A plausible mechanism is only the start of evaluating a physique claim.',
 'Atrae la idea de aislar una parte de la biología de GH relacionada con grasa sin reproducir todas sus acciones. Es un fragmento modificado, no intercambiable con cualquier producto llamado fragmento de HGH. Un mecanismo plausible es apenas el inicio para evaluar una promesa estética.',
 'The mechanism does not establish dependable weight loss, spot reduction or freedom from adverse effects.',
 'El mecanismo no demuestra pérdida de peso fiable, reducción localizada ni ausencia de efectos adversos.'],
['Epitalon',
 'Telomeres, sleep rhythms and “biological age”: the longevity vocabulary surrounding Epitalon.',
 'Telómeros, ritmos de sueño y “edad biológica”: el vocabulario de longevidad que rodea a Epitalon.',
 'The appeal is maintaining function over time rather than chasing a short-term boost. Telomeres and cellular-aging markers are research tools, not a countdown of years left to live. A change in a cellular assay cannot establish younger organs, better sleep or longer human life.',
 'El atractivo es mantener función con el tiempo, no un impulso momentáneo. Telómeros y marcadores celulares son herramientas de investigación, no una cuenta regresiva de años por vivir. Cambiar un ensayo celular no demuestra órganos más jóvenes, mejor sueño ni mayor vida humana.',
 'Human longevity claims exceed the available evidence; “age reversal” is not an established outcome.',
 'Las afirmaciones de longevidad humana exceden la evidencia; “revertir la edad” no es un resultado establecido.'],
['Thymosin Alpha-1',
 'Immune resilience rather than “more immunity”: the distinction behind this thymic-peptide conversation.',
 'Resiliencia inmunitaria, no simplemente “más defensas”: la distinción detrás de este péptido tímico.',
 'The community interest is a well-regulated response to challenges. Immune modulation is not the same as turning every immune signal up; excessive and inadequate responses can both be problematic. Studies in a defined illness cannot be assumed to show fewer sick days in healthy people.',
 'El interés es una respuesta bien regulada frente a desafíos. Modular inmunidad no significa subir todas las señales: tanto una respuesta excesiva como insuficiente pueden ser problemáticas. Estudios en una enfermedad definida no demuestran menos días enfermo en personas sanas.',
 'Clinical context, immune status and the specific indication determine how evidence should be read.',
 'El contexto clínico, el estado inmunitario y la indicación concreta determinan cómo interpretar la evidencia.'],
['Thymalin',
 'Immune aging and resilience: why thymus-derived preparations appear in longevity discussions.',
 'Envejecimiento inmunitario y resiliencia: por qué las preparaciones tímicas aparecen en longevidad.',
 'The attraction is preserving the immune system’s function with age. Thymalin is a preparation rather than an interchangeable name for thymosin alpha-1. Its composition and study context matter; the fact that two references relate to the thymus does not give them the same effects.',
 'El atractivo es conservar la función inmunitaria con la edad. Thymalin es una preparación, no otro nombre para timosina alfa-1. Importan composición y contexto de estudio: relacionarse con el timo no da a dos referencias los mismos efectos.',
 'An immune-aging narrative does not establish rejuvenation or routine infection prevention.',
 'Una narrativa de envejecimiento inmunitario no demuestra rejuvenecimiento ni prevención habitual de infecciones.'],
['LL-37',
 'Innate defence, skin and “antimicrobial” claims: a powerful-sounding label that needs careful context.',
 'Defensa innata, piel y afirmaciones “antimicrobianas”: una etiqueta que exige contexto cuidadoso.',
 'LL-37 is part of host-defence biology, which explains interest in wounds and skin. But activity against a microbe in a laboratory is not the same as safely treating an infection. Its inflammatory effects also make “boosting natural defence” an incomplete description.',
 'LL-37 forma parte de la defensa del organismo, lo que explica el interés en heridas y piel. Actuar contra un microbio en laboratorio no equivale a tratar una infección de forma segura. Sus efectos inflamatorios hacen incompleta la frase “potenciar defensas naturales”.',
 'It is not a substitute for diagnosis or established antimicrobial treatment.',
 'No sustituye un diagnóstico ni un tratamiento antimicrobiano establecido.'],
['VIP',
 'Inflammatory balance and autonomic wellbeing: the broad wellness conversation around vasoactive intestinal peptide.',
 'Equilibrio inflamatorio y bienestar autonómico: la conversación amplia alrededor del péptido intestinal vasoactivo.',
 'VIP is discussed in some communities through complex symptom and environmental-illness narratives. It also participates in vascular and gastrointestinal physiology. That broad biology makes it important to ask which condition and endpoint were actually studied rather than treating it as a general reset.',
 'VIP se comenta en algunas comunidades dentro de narrativas de síntomas complejos y enfermedad ambiental. También participa en fisiología vascular y gastrointestinal. Esa amplitud obliga a preguntar qué condición y resultado se estudiaron, no a presentarlo como un reinicio general.',
 'A broad signalling role does not establish a “detox”, autonomic reset or safe wellness intervention.',
 'Una función amplia de señalización no demuestra un “detox”, un reinicio autonómico ni una intervención de bienestar segura.'],
['FOXO4',
 '“Zombie cells” and senolytics: the attention-grabbing language behind senescence research.',
 '“Células zombi” y senolíticos: el lenguaje llamativo detrás de la investigación de senescencia.',
 'Senescent cells have stopped dividing and can influence their surroundings. The community interest is clearing harmful senescent-cell activity, but FOXO4 is a protein target; FOXO4-DRI is a particular experimental peptide. The short catalogue name cannot establish that molecular identity.',
 'Las células senescentes han dejado de dividirse y pueden influir en su entorno. Interesa eliminar actividad senescente perjudicial, pero FOXO4 es una proteína diana; FOXO4-DRI es un péptido experimental concreto. El nombre corto del catálogo no establece esa identidad molecular.',
 'Animal senolytic findings do not prove human age reversal, and not every senescent-cell function is harmful.',
 'Los hallazgos senolíticos animales no prueban reversión de edad humana; no toda función de las células senescentes es perjudicial.'],
['Kisspeptin-10',
 'Hormone signalling, reproductive function and libido: interest in an upstream reproductive-axis signal.',
 'Señalización hormonal, función reproductiva y libido: interés en una señal inicial del eje reproductivo.',
 'Kisspeptin acts upstream of downstream reproductive hormones, which is why “restart the axis” appears in community language. That phrase oversimplifies feedback loops and individual clinical causes. A hormone response does not by itself demonstrate fertility, sexual wellbeing or long-term endocrine recovery.',
 'Kisspeptina actúa antes de otras hormonas reproductivas; de ahí la frase comunitaria “reiniciar el eje”. Esa frase simplifica circuitos de retroalimentación y causas clínicas individuales. Una respuesta hormonal no demuestra por sí sola fertilidad, bienestar sexual ni recuperación endocrina sostenida.',
 'It is not a general testosterone booster or a self-directed fertility solution.',
 'No es un potenciador general de testosterona ni una solución de fertilidad por cuenta propia.'],
['Glutathione',
 'The “master antioxidant”, recovery and skin-glow conversation—translated into redox biology rather than detox promises.',
 'El “antioxidante maestro”, recuperación y luminosidad de piel: entender la biología redox sin promesas de detox.',
 'Glutathione is a tripeptide made from three amino acids. It participates in cellular antioxidant systems, but its normal role does not mean every product improves recovery or appearance. “Oxidative stress” is a biological concept, not a diagnosis that can be made from tiredness alone.',
 'Glutatión es un tripéptido formado por tres aminoácidos. Participa en sistemas antioxidantes celulares, pero su función normal no implica que todo producto mejore recuperación o apariencia. “Estrés oxidativo” es un concepto biológico, no un diagnóstico que se haga solo por cansancio.',
 'Formulation and measured outcomes matter; broad detox, skin-lightening and anti-aging promises are not interchangeable evidence.',
 'Importan la formulación y los resultados medidos; detox, aclaramiento de piel y anti-aging no son evidencias intercambiables.'],
['PT-141',
 'Desire and libido—not the same thing as physical sexual performance: the distinction behind PT-141.',
 'Deseo y libido, que no son lo mismo que desempeño sexual físico: la distinción detrás de PT-141.',
 'Also known as bremelanotide, it enters the conversation through melanocortin signalling. Sexual desire, arousal and erectile function are different outcomes. The existence of a prescription medicine for a defined indication does not make every PT-141 product a universal libido enhancer.',
 'También llamado bremelanotide, aparece por la señalización de melanocortinas. Deseo, excitación y función eréctil son resultados diferentes. Que exista un medicamento con indicación definida no convierte a todo producto PT-141 en un potenciador universal de libido.',
 'Clinical eligibility and cardiovascular effects matter; research labels do not confer prescription-product equivalence.',
 'Importan la elegibilidad clínica y los efectos cardiovasculares; una etiqueta de investigación no equivale a un medicamento de prescripción.'],
['HCG',
 'Fertility and hormone-axis discussions: why hCG is not simply another “testosterone optimization” ingredient.',
 'Fertilidad y eje hormonal: por qué hCG no es simplemente otro ingrediente de “optimización de testosterona”.',
 'Human chorionic gonadotropin is a hormone with LH-like activity. It appears in fertility conversations and in online “PCT” language, meaning post-cycle therapy. Describing that vocabulary is not endorsing a cycle or a recovery plan; underlying endocrine causes and fertility goals require individual assessment.',
 'La gonadotropina coriónica humana es una hormona con actividad similar a LH. Aparece en fertilidad y en el término “PCT”, terapia posciclo. Explicar ese vocabulario no respalda ciclos ni planes de recuperación: las causas endocrinas y los objetivos de fertilidad requieren valoración individual.',
 'A hormone response cannot confirm restored fertility or make unsupervised endocrine manipulation safe.',
 'Una respuesta hormonal no confirma fertilidad restaurada ni vuelve segura la manipulación endocrina sin supervisión.'],
['Melanotan I',
 'Pigmentation and the “sunless tan” idea: separating melanocortin research from cosmetic assumptions.',
 'Pigmentación y la idea de “bronceado sin sol”: separar investigación de melanocortinas de suposiciones cosméticas.',
 'This name is associated with afamelanotide-related discussions. A regulated formulation for a specific condition and a research product sold for tanning are not equivalent. More pigment should never be read as permission for greater UV exposure or as a replacement for sun protection.',
 'El nombre se asocia a conversaciones sobre afamelanotide. Una formulación regulada para una condición concreta y un producto de investigación para bronceado no son equivalentes. Más pigmento no da permiso para aumentar exposición UV ni reemplaza protección solar.',
 'Cosmetic tanning claims do not establish safety, product identity or protection from skin damage.',
 'Las promesas de bronceado cosmético no establecen seguridad, identidad del producto ni protección contra daño cutáneo.'],
['Melanotan II',
 'Tanning, appetite and libido appear together in discussion because this is not a skin-only signal.',
 'Bronceado, apetito y libido aparecen juntos porque no es una señal limitada a la piel.',
 'The attraction is often cosmetic, yet melanocortin signalling reaches beyond pigmentation. Reports of changes in appetite or sexual function should not be packaged as bonus benefits. Multiple effects make the risk picture more complex, not the product more versatile.',
 'El atractivo suele ser cosmético, pero las melanocortinas actúan más allá de la pigmentación. Los relatos de cambios de apetito o función sexual no deben empaquetarse como beneficios extra. Múltiples efectos complican el perfil de riesgo; no vuelven al producto más versátil.',
 'It is not interchangeable with Melanotan I, and a tanning effect does not establish safe cosmetic use.',
 'No es intercambiable con Melanotan I; un efecto de bronceado no demuestra uso cosmético seguro.'],
['Snap-8',
 'Expression lines and “Botox-like” skincare: a topical-peptide conversation, not injectable toxin equivalence.',
 'Líneas de expresión y cosmética “tipo Botox”: una conversación de péptidos tópicos, no equivalencia con toxina inyectable.',
 'The appeal is a smoother-looking skin surface without treating every wrinkle as the same problem. Expression lines, dehydration and loss of skin support have different causes. For a cosmetic peptide, the finished formula and delivery through skin matter as much as an ingredient-level laboratory result.',
 'El atractivo es una piel de aspecto más liso, pero no toda arruga tiene la misma causa. Líneas de expresión, deshidratación y pérdida de soporte son diferentes. En un péptido cosmético, la fórmula final y el paso por la piel importan tanto como un resultado del ingrediente en laboratorio.',
 '“Botox-like” is a marketing comparison, not proof of equal effect, duration or medical use.',
 '“Tipo Botox” es una comparación comercial, no prueba de igual efecto, duración ni uso médico.'],
['Lemon Bottle',
 '“Stubborn fat” and contouring claims: a branded-formulation discussion that should not be presented as peptide science.',
 '“Grasa rebelde” y contorno corporal: una formulación comercial que no debe presentarse como ciencia de péptidos.',
 'The appeal is changing small areas of appearance rather than overall metabolic health. Lemon Bottle is a brand/formulation label, not a defined peptide or an established synonym for safe fat reduction. Ingredient stories and before-and-after images cannot demonstrate what a finished product does.',
 'Atrae cambiar zonas pequeñas de la apariencia, no la salud metabólica general. Lemon Bottle es una etiqueta comercial, no un péptido definido ni sinónimo de reducción de grasa segura. Relatos sobre ingredientes y fotos de antes/después no demuestran el efecto del producto final.',
 'The FDA has addressed LemonBottle marketing in a warning letter; unapproved fat-dissolving products can cause serious harm.',
 'La FDA ha abordado publicidad de LemonBottle en una carta de advertencia; los productos no aprobados para disolver grasa pueden causar daño grave.'],
['Botulinum Toxin',
 'Expression lines and a “rested look”: a neuromuscular aesthetic treatment, not a regenerative peptide stack.',
 'Líneas de expresión y “aspecto descansado”: una intervención neuromuscular estética, no un stack regenerativo.',
 'The discussion is about muscle activity that contributes to expression lines, rather than rebuilding collagen or improving every aspect of skin quality. Botulinum toxin products are biologic medicines. Their labelled units and formulations cannot be assumed equivalent across brands.',
 'La conversación es sobre actividad muscular que contribuye a líneas de expresión, no reconstruir colágeno ni mejorar toda la calidad de piel. Las toxinas botulínicas son medicamentos biológicos. Sus unidades y formulaciones no se consideran equivalentes entre marcas.',
 'Professional clinical assessment is essential; this reference is not guidance for self-administration.',
 'La valoración clínica profesional es esencial; esta referencia no guía la autoadministración.'],
['Hyaluronic Acid',
 'Hydration, “skin plumpness” and joint comfort: one name covering very different product contexts.',
 'Hidratación, piel más “rellena” y bienestar articular: un nombre que abarca productos muy diferentes.',
 'Hyaluronic acid is a polysaccharide, not a peptide. A topical moisturizer, a dermal filler and a joint product are not interchangeable interventions. The community language of “plumping” needs that distinction: surface hydration and adding tissue volume are not the same effect.',
 'El ácido hialurónico es un polisacárido, no un péptido. Un hidratante tópico, un relleno dérmico y un producto articular no son intervenciones intercambiables. Hablar de piel más “rellena” requiere distinguir hidratación superficial de aportar volumen al tejido.',
 'Evidence and risks belong to the specific formulation and route, not the ingredient name alone.',
 'La evidencia y los riesgos dependen de formulación y vía concretas, no solo del nombre del ingrediente.'],
['CJC-1295 (No DAC) + Ipamorelin',
 'The GH-axis “recovery stack”: two signalling approaches discussed around sleep, recovery and recomposition.',
 'El “stack de recuperación” del eje GH: dos enfoques comentados alrededor de sueño, recuperación y recomposición.',
 'The rationale combines a GHRH-related signal with a ghrelin-receptor secretagogue. In community language, a stack means a combination chosen around a goal; it is not a scientific evidence grade. A plausible complementary mechanism does not establish better outcomes from a premixed product.',
 'La lógica combina una señal relacionada con GHRH y un secretagogo del receptor de grelina. En lenguaje comunitario, stack es una combinación elegida alrededor de un objetivo; no es un nivel de evidencia. La complementariedad teórica no demuestra mejores resultados de una premezcla.',
 'The exact no-DAC identity, proportions and combination evidence must be established separately.',
 'La identidad exacta sin DAC, las proporciones y la evidencia de la combinación deben establecerse por separado.'],
['CagriSema Standard',
 'Amylin plus GLP-1: the satiety-focused combination behind the CagriSema conversation.',
 'Amilina más GLP-1: la combinación centrada en saciedad detrás de CagriSema.',
 'The interest is approaching appetite through different pathways with cagrilintide and semaglutide. “Standard” is a catalogue label, not the name of a trial formulation. Research on the combination is meaningful, but its identity, ratio and quality cannot be inferred from that label.',
 'Interesa abordar el apetito por vías diferentes con cagrilintide y semaglutide. “Standard” es una etiqueta de catálogo, no el nombre de una formulación de ensayo. La investigación de la combinación importa, pero la etiqueta no determina identidad, proporción ni calidad.',
 'Clinical combination results do not validate an arbitrary research blend sold under the same shorthand.',
 'Los resultados clínicos de la combinación no validan una mezcla de investigación arbitraria con el mismo nombre abreviado.'],
['CagriSema High Concentration',
 'The same appetite-pathway pairing with a concentration label—not a claim of better fat loss.',
 'La misma pareja de vías del apetito con una etiqueta de concentración, no una promesa de mayor pérdida de grasa.',
 'High concentration describes material per volume, not stronger evidence or superior results. The community goal remains satiety and body composition. Comparing this entry with the standard reference should start with exact composition and concentration rather than assuming that “more concentrated” means more effective.',
 'Alta concentración describe material por volumen, no evidencia más sólida ni resultados superiores. El objetivo sigue siendo saciedad y composición corporal. Comparar con la referencia estándar empieza por composición y concentración exactas, no por suponer que “más concentrado” es más eficaz.',
 'A concentration difference does not create a new evidence base or establish product equivalence to clinical CagriSema.',
 'Una diferencia de concentración no crea nueva evidencia ni equivalencia del producto con CagriSema clínico.'],
['BPC-157 + TB-500 Standard',
 'The “Wolverine stack” nickname: BPC-157 plus TB-500 in the return-to-training conversation.',
 'El apodo “Wolverine stack”: BPC-157 más TB-500 en la conversación de volver a entrenar.',
 'The nickname expresses a hope for accelerated recovery, not a demonstrated healing ability. Discussions combine BPC-related tissue research with thymosin-beta-4-related biology. Individual-compound findings cannot show that the blend repairs tendons, muscles or joints faster than either component alone.',
 'El apodo expresa la esperanza de recuperarse más rápido, no una capacidad demostrada de reparación. Combina investigación de BPC con biología relacionada con timosina beta-4. Hallazgos individuales no prueban que la mezcla repare tendones, músculos o articulaciones más rápido que sus componentes.',
 'The combination’s human efficacy and safety cannot be assumed from its popularity or nickname.',
 'La eficacia y seguridad humana de la combinación no se deducen de su popularidad ni de su apodo.'],
['BPC-157 + TB-500 High Concentration',
 'The recovery-stack discussion in a more concentrated presentation—not a “faster healing” category.',
 'La conversación del stack de recuperación en una presentación más concentrada, no una categoría de “reparación más rápida”.',
 'The goals mirror the standard pairing: movement, comfort and return to activity. Concentration only describes how much material is present per volume. It cannot tell you the blend’s biological outcome, and it does not resolve the identity ambiguity around TB-500.',
 'Los objetivos son los de la pareja estándar: movimiento, bienestar y regreso a la actividad. Concentración solo describe cuánto material hay por volumen. No indica el resultado biológico de la mezcla ni resuelve la ambigüedad de identidad de TB-500.',
 'Higher concentration is not proof of higher benefit, greater selectivity or safer recovery.',
 'Mayor concentración no prueba mayor beneficio, más selectividad ni recuperación más segura.'],
['GLOW',
 'BPC-157 + TB-500 + GHK-Cu: the named stack connecting recovery goals with skin-quality conversations.',
 'BPC-157 + TB-500 + GHK-Cu: el stack que conecta objetivos de recuperación con calidad de piel.',
 'The appeal is a “repair plus glow” narrative: BPC and TB-related recovery discussions alongside the copper-peptide skin conversation. GLOW is a combination name, not a new molecule. Its ingredients describe the concept; the label alone does not establish ratios, identity or a tested final formulation.',
 'El atractivo es la narrativa “recuperación más glow”: las conversaciones de BPC y TB junto al interés cutáneo del péptido de cobre. GLOW es el nombre de una combinación, no una molécula nueva. Sus ingredientes describen el concepto; la etiqueta no establece proporciones, identidad ni formulación final probada.',
 'Evidence for separate components cannot demonstrate synergy, collagen gains or injury recovery from GLOW itself.',
 'La evidencia separada de los componentes no demuestra sinergia, aumento de colágeno ni recuperación de lesiones con GLOW.'],
['KLOW',
 'GLOW plus KPV: BPC-157 + TB-500 + GHK-Cu + KPV, with an added inflammatory-signalling conversation.',
 'GLOW más KPV: BPC-157 + TB-500 + GHK-Cu + KPV, con una conversación adicional sobre señalización inflamatoria.',
 'KLOW extends the recovery-and-skin narrative with KPV’s gut and inflammatory-pathway interest. It should be described as a distinct four-component combination, not “stronger GLOW”. Adding a pathway also adds uncertainty; more ingredients do not automatically deliver broader or better results.',
 'KLOW amplía la narrativa de recuperación y piel con el interés intestinal e inflamatorio de KPV. Es una combinación distinta de cuatro componentes, no “GLOW más fuerte”. Agregar una vía también agrega incertidumbre; más ingredientes no producen automáticamente más o mejores resultados.',
 'The full four-component formulation needs its own evidence; ingredient count cannot establish safety or synergy.',
 'La formulación completa de cuatro componentes necesita evidencia propia; el número de ingredientes no establece seguridad ni sinergia.'],
['Bacteriostatic Water / PBS',
 'Laboratory vehicles, not biohacking actives: water and buffered saline are different references.',
 'Vehículos de laboratorio, no activos de biohacking: agua y solución salina tamponada son referencias diferentes.',
 'This combined catalogue entry must not imply interchangeability. Bacteriostatic water and PBS differ in composition and purpose; PBS is defined by its buffer and salts. A solvent choice affects a laboratory preparation, but none of these materials supplies a performance, recovery or longevity benefit.',
 'La entrada conjunta no debe implicar que sean intercambiables. Agua bacteriostática y PBS difieren en composición y finalidad; PBS se define por su tampón y sales. Elegir un solvente afecta una preparación de laboratorio, pero estos materiales no aportan beneficios de rendimiento, recuperación ni longevidad.',
 'Compatibility and suitability require product-specific documentation. “Bacteriostatic” does not mean it sterilizes a preparation.',
 'Compatibilidad e idoneidad requieren documentación del producto. “Bacteriostático” no significa que esterilice una preparación.'],
['Benzyl Alcohol 0.9%',
 'A preservative-related laboratory reference—not a recovery compound or a substitute for a finished diluent.',
 'Una referencia de laboratorio relacionada con conservantes, no un compuesto de recuperación ni sustituto de un diluyente terminado.',
 'Benzyl alcohol can appear in discussions of preserved laboratory materials. The percentage alone does not identify the full solvent, sterility or compatibility of a product. Its presence is a formulation characteristic, not a biohacking benefit or permission to improvise a preparation.',
 'El alcohol bencílico aparece al hablar de materiales de laboratorio con conservante. El porcentaje no identifica todo el solvente, su esterilidad ni compatibilidad. Su presencia es una característica de formulación, no un beneficio de biohacking ni permiso para improvisar preparaciones.',
 'Preservation is not sterilization; no personal-use or preparation instructions are implied.',
 'Conservar no es esterilizar; no se implican instrucciones de preparación ni de uso personal.'],
['Acetic Acid 0.6%',
 'A laboratory acidity and solubility reference—not a biohacking ingredient with human benefits.',
 'Una referencia de acidez y solubilidad en laboratorio, no un ingrediente de biohacking con beneficios humanos.',
 'Acetic acid appears in some laboratory workflows because acidity can affect compound behaviour. A percentage does not establish compatibility with every peptide, stability over time or suitability outside that workflow. It belongs in research tools rather than in a list of performance actives.',
 'El ácido acético aparece en algunos procesos de laboratorio porque la acidez afecta el comportamiento de compuestos. Un porcentaje no establece compatibilidad con todo péptido, estabilidad en el tiempo ni idoneidad fuera de ese proceso. Pertenece a herramientas, no a activos de rendimiento.',
 'Laboratory solvent information is not guidance for human administration or improvised mixing.',
 'La información de solventes de laboratorio no guía administración humana ni mezclas improvisadas.']
].map(([name,summaryEn,summaryEs,contextEn,contextEs,boundaryEn,boundaryEs])=>[name,{
 en:{summary:summaryEn,context:contextEn,boundary:boundaryEn},
 es:{summary:summaryEs,context:contextEs,boundary:boundaryEs}
}]));

// Selected sources support the stated distinction, not every community claim.
const PEPTORA_COMMUNITY_SOURCES = {
 'Retatrutide':[['https://pubmed.ncbi.nlm.nih.gov/37366315/','Human obesity trial · triple-receptor agonism (2023)','Ensayo humano de obesidad · agonismo de tres receptores (2023)']],
 'MOTS-c':[['https://pubmed.ncbi.nlm.nih.gov/33473109/','Exercise biology · human observations and mouse experiments (2021)','Biología del ejercicio · observaciones humanas y experimentos en ratones (2021)']],
 'Tesamorelin':[['https://pubmed.ncbi.nlm.nih.gov/23015655/','Visceral fat · trial in adults with obesity and reduced GH secretion (2012)','Grasa visceral · ensayo en adultos con obesidad y secreción reducida de GH (2012)']],
 'CJC-1295 (With DAC)':[['https://pubmed.ncbi.nlm.nih.gov/16352683/','Long-acting CJC-1295 · human GH/IGF-1 study (2006)','CJC-1295 de acción prolongada · estudio humano de GH/IGF-1 (2006)']],
 'CJC-1295 (No DAC)':[['https://pubmed.ncbi.nlm.nih.gov/16352683/','Compare carefully: this study is long-acting CJC-1295, not no DAC','Compara con cuidado: este estudio es de CJC-1295 prolongado, no sin DAC']],
 'Semax':[['https://pubmed.ncbi.nlm.nih.gov/29798983/','Clinical context: stroke rehabilitation, not healthy-user enhancement (2018)','Contexto clínico: rehabilitación tras ictus, no mejora en usuarios sanos (2018)']],
 'Selank':[['https://pubmed.ncbi.nlm.nih.gov/18454096/','Anxiety-related clinical study · interpret population and limitations (2008)','Estudio clínico relacionado con ansiedad · considerar población y límites (2008)']],
 '5-Amino-1MQ':[['https://pubmed.ncbi.nlm.nih.gov/29155147/','NNMT inhibition · mouse obesity experiment (2017)','Inhibición de NNMT · experimento de obesidad en ratones (2017)']],
 'FOXO4':[['https://pubmed.ncbi.nlm.nih.gov/28340339/','FOXO4-DRI · preclinical senescence study (2017)','FOXO4-DRI · estudio preclínico de senescencia (2017)']],
 'Glutathione':[['https://pubchem.ncbi.nlm.nih.gov/compound/Glutathione','Molecular identity · PubChem tripeptide reference','Identidad molecular · referencia de tripéptido en PubChem']],
 'SS-31':[['https://www.fda.gov/drugs/drug-trials-snapshots/drug-trials-snapshots-forzinity','FDA · elamipretide in Barth syndrome, not general longevity','FDA · elamipretide en síndrome de Barth, no longevidad general']],
 'NAD+':[['https://pubmed.ncbi.nlm.nih.gov/31412242/','Example of the distinction: this human study used NR, not NAD+ (2019)','Ejemplo de la distinción: este estudio humano usó NR, no NAD+ (2019)']],
 'Lemon Bottle':[['https://www.fda.gov/inspections-compliance-enforcement-and-criminal-investigations/warning-letters/amazoncom-inc-695821-03032025','FDA warning letter · LemonBottle marketing (2025)','Carta de advertencia FDA · publicidad de LemonBottle (2025)']],
 'CagriSema Standard':[['https://pubmed.ncbi.nlm.nih.gov/40544432/','Clinical cagrilintide–semaglutide trial · not this catalogue formulation (2025)','Ensayo clínico de cagrilintide–semaglutide · no de esta formulación de catálogo (2025)']],
 'CagriSema High Concentration':[['https://pubmed.ncbi.nlm.nih.gov/40544432/','Clinical cagrilintide–semaglutide trial · not this concentration label (2025)','Ensayo clínico de cagrilintide–semaglutide · no de esta etiqueta de concentración (2025)']]
};
for(const name of ['BPC-157','TB-500 (Thymosin B4 Acetate)','KPV','GLOW','KLOW']){
 PEPTORA_COMMUNITY_SOURCES[name]=[['https://www.fda.gov/drugs/human-drug-compounding/certain-bulk-drug-substances-use-compounding-may-present-significant-safety-risks','FDA safety context for substances · not evidence of blend efficacy','Contexto de seguridad FDA para sustancias · no demuestra eficacia de mezclas']];
}

// Shared cards and global search use the same concise introduction on every page.
for(const [name,entry] of Object.entries(PEPTORA_COMMUNITY)){
 for(const lang of ['en','es']){
  const profile=BIOHACKING_LENS_BY_PRODUCT[lang][name];
  if(profile)profile.community=entry[lang].summary;
 }
}
